# Generated by Django 6.0.6 on 2026-06-23 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='membership_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
